#!/bin/zsh

###################
# 1 environnement #
###################

export GWT_EXTERNAL_BROWSER=/usr/bin/firefox
export PATH=$PATH:/usr/lib/perl5/vendor_perl/bin/:/opt/java/jre/bin:~/.node/bin/:/home/mumu/bin:

export EDITOR="vimx"
export BROWSER=firefox
export GPGKEY=1193ADBC
export WORDCHARS="_-"
if [ -x /usr/bin/virtualenvwrapper.sh ]; then
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2
    export WORKON_HOME=~/.envs
    export PROJECT_HOME=~/kozea
    export PIP_VIRTUALENV_BASE=$WORKON_HOME
    export PIP_RESPECT_VIRTUALENV=true
    source /usr/bin/virtualenvwrapper.sh
fi
# Host specific configuration
case $HOST in
    archwork)
        export http_proxy=http://10.20.68.3:8080
        export https_proxy=http://10.20.68.3:8080
        export ftp_proxy=http://10.20.68.3:8080
    ;;
esac
export PYMACS_PYTHON=python2
export PYTHONSTARTUP="$ZDOTDIR/.pythonrc.py"

export LESS='--RAW-CONTROL-CHARS --tabs=8 -r --quiet'
export LESSOPEN="|  pygmentize %s"

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.
