#!/bin/zsh

__motd() {
    HOSTNAME=`uname -n`
    KERNEL=`uname -r`
    CPU=`uname -p`
    ARCH=`uname -m`
    UPTIME=$(</proc/uptime)
    UPTIME=${UPTIME%%.*}

    UPTIME="$(( UPTIME/60/60/24 )) days, $(( UPTIME/60/60%24 )) hours, $(( UPTIME/60%60 )) minutes, $(( UPTIME%60 )) seconds"
    SHELLNAME=`echo $SHELL | cut -d '/' -f 3`
    USEDMEM=`free -m | grep Mem | sed -r "s/Mem:\s+([0-9]+)\s+([0-9]+).*/${red__}\2M${blue__} \/ \1M/"`
    USEDSWAP=`free -m | grep Swap | sed -r "s/Swap:\s+([0-9]+)\s+([0-9]+).*/${green__}\2M${blue__} \/ \1M/"`
    FREEDISK=`df -Tlh -x tmpfs -x devtmpfs --total | grep total | sed -r "s/total\s+\-\s+([0-9.]+\w)\s+([0-9.]+\w).*/${yellow__}\2 ${blue__}\/ \1/"`

    echo -e "${blue_}//=========================---${____}"
    echo -e "${blue_}\\ ${cyan_}User:${blue__}     $USER${____}"
    echo -e "${blue_}\\ ${cyan_}Hostname:${blue__} $HOSTNAME${____}"
    echo -e "${blue_}\\ ${cyan_}Kernel:${blue__}   $KERNEL${____}"
    echo -e "${blue_}\\ ${cyan_}Uptime:${blue__}   $UPTIME${____}"
    echo -e "${blue_}\\ ${cyan_}Shell:${blue__}    $SHELLNAME${____}"
    echo -e "${blue_}\\ ${cyan_}Terminal:${blue__} $TERM${____}"
    echo -e "${blue_}\\ ${cyan_}Cpu:${blue__}      $CPU${____}"
    echo -e "${blue_}\\ ${cyan_}Mem:${blue__}      $USEDMEM${____}"
    echo -e "${blue_}\\ ${cyan_}Swap:${blue__}     $USEDSWAP${____}"
    echo -e "${blue_}\\ ${cyan_}Disk:${blue__}     $FREEDISK${____}"
    echo -e "${blue_}\\=========================---${____}"
}
